### ISSUE TITLE
Create Report page for post/user page

### ISSUE THREAD

**Issue by Kyj1n** [shop-manoa/shop-manoa#5]
Do all work for this task in a branch called issue-06.

**Comment by 000Aym612** [comment]
Created a page for reports of post and users.
The page is only accessible by admin account and shows all reports by registered users

Each report has:
- types: Post or User
- category: Spam, iligal stuff etc.
- details: Explanation why you think the post(or user) is inappropriate
- owner: Tells us which account filled out the form
